repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7 
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-requests
          - pytest>=8.3.5
          - pytest-mock>=3.14.0
        args: [--config-file=mypy.ini]
        exclude: ^(docs/|examples/)